language: postgres
dialect: 10.7
for:
  objects:
    search:
      - 'src/domain/objects/*.ts'
    include:
      - 'User'
      - 'Home'
    exclude:
      - 'Car'
generates:
  daos:
    to: src/data/dao
    using:
      log: src/util/log#log
      DatabaseConnection: src/util/database/getDbConnection#DatabaseConnection
  schema:
    config: codegen.schema.yml
  control:
    config: provision/schema/control.yml
  code:
    config: codegen.sql.yml
